djia_stocks = {
    '3m':'MMM',
    'american express':'AXP',
    'amgen':'AMGN',
    'apple':'AAPL',
    'boeing':'BA',
    'caterpillar':'CAT',
    'bhevron':'CVX',
    'cisco':'KO',
    'disney':'DIS',
    'dow':'DOW',
    'goldman sachs':'GS',
    'home depot':'HD',
    'honeywell':'HON',
    'ibm':'IBM',
    'intel':'INTC',
    'jpmorgan chase':'JPM',
    'mcDonald':'MCD',
    'merck':'MRK',
    'microsoft':'MSFT',
    'nike':'NKE',
    'salesforce':'CRM',
    'travelers':'TRV',
    'unitedhealth':'UNH',
    'verizon':'VZ',
    'walgreens boots alliance':'WBA',
    'walmart':'WMT',
}

djia_stocks_reverse = { v:k for k,v in djia_stocks.items() }

stocks_subreddits = [
    'wallstreetbets',
    'stocks',
    'investing',
    'investing_discussion',
    'StockMarket',
    'ValueInvesting',
    'Stock_Picks',
    'Daytrading',
]