djia_stocks = {
    '3M':'MMM',
    'American Express':'AXP',
    'Amgen':'AMGN',
    'Apple':'AAPL',
    'Boeing':'BA',
    'Caterpillar':'CAT',
    'Chevron':'CVX',
    'Cisco':'KO',
    'Disney':'DIS',
    'Dow':'DOW',
    'Goldman Sachs':'GS',
    'Home Depot':'HD',
    'Honeywell':'HON',
    'IBM':'IBM',
    'Intel':'INTC',
    'JPMorgan Chase':'JPM',
    'McDonald\'s':'MCD',
    'Merck':'MRK',
    'Microsoft':'MSFT',
    'Nike':'NKE',
    'Salesforce':'CRM',
    'Travelers':'TRV',
    'UnitedHealth':'UNH',
    'Verizon':'VZ',
    'Walgreens Boots Alliance':'WBA',
    'Walmart':'WMT',
}

stocks_subreddits = [
    'wallstreetbets',
    'stocks',
    'investing',
    'investing_discussion',
    'StockMarket',
    'ValueInvesting',
    'Stock_Picks',
    'Daytrading',
]